// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icneohhatehkrouckxnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljbmVvaGhhdGVoa3JvdWNreG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODMyOTcsImV4cCI6MjA2ODU1OTI5N30.Ob_YSn62makYyO-uBXZENDPa9enmBq8G9lIbAAvYX6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});